AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: API for utility functionality on ogbix
Globals:
  Function:
    Runtime: python3.12
    Tracing: Active
Resources:
  ChartBuilder:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: chartbuilder/
      Handler: chartbuilder.handler                          
      Runtime: python3.12
      MemorySize: 3008
      Timeout: 300
      Policies: 
      - AmazonDynamoDBFullAccess
      - AmazonS3ReadOnlyAccess
